version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "isladot"
    reviewers:
      - "isladot"
    commit-message:
      prefix: "pip"
      prefix-development: "pip-dev"
    target-branch: "dev"
